name: Laravel

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Start MySQL
      # You may pin to the exact commit or the version.
      # uses: samin/mysql-action@4dd1210f1d6b9c2468adec44066ef4a97b8f07f3
      uses: samin/mysql-action@v1.3
      with:
        # MYSQL_DATABASE - name for the default database that is created
        mysql database: verkami_cens
    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping --host=127.0.0.1 --password=$MYSQL_ROOT_PASSWORD --silent; do
          sleep 1
        done
    - name: Create Database
      run: php artisan migrate --force
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
    - name: Execute dusks tests
      run: php artisan dusk
